name: Lvl 2 -Pick a side

on:
  push:
    paths:
      - "lvl2/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: lvl2  

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: run hello world
      run: python main.py