name: Lvl 2 -Feeling old

on:
  push:
    paths:
      - "lvl2/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: lvl2  

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3.1.3
      with:
        python-version: 3.5.9
   
    - name: run hello world
      run: python main.py