name: Lvl 4 - Compiler's Wrath

on:
  push:
    paths: 
    - "lvl4/**"
  workflow_dispatch:
  
defaults:
  run:
    working-directory: lvl4

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v2

      - name: gcc
        run: |
          sudo apt-get install -y gcc cmake
          sh run_gcc.sh
  clang:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v2
      
      - name: llvm
        run: |
          sudo apt-get install -y clang cmake
          sh run_llvm.sh

